name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/*" ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.2.0

    - name: Print git ref
      run: echo ${{ github.ref }} && echo ${{ github.ref_name }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/s390x,linux/ppc64le
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
        build-args: |
          GOLANG_VERSION=${{ vars.GOLANG_VERSION }}
